// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM-p7d31jsta9MlimU3d-A9hexWQe3im0',
    appId: '1:984797892872:web:af34ba0169704d00251cbd',
    messagingSenderId: '984797892872',
    projectId: 'chat-near-by',
    authDomain: 'chat-near-by.firebaseapp.com',
    storageBucket: 'chat-near-by.appspot.com',
    measurementId: 'G-J7DK00P1LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh2Fih0yPME_TD7Ld4wttH7miBbCx0c1U',
    appId: '1:984797892872:android:9123f30cbf29a8da251cbd',
    messagingSenderId: '984797892872',
    projectId: 'chat-near-by',
    storageBucket: 'chat-near-by.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRB1I0Flk1Zr5GhOzgbQqvmKtThdwiDsE',
    appId: '1:984797892872:ios:5a122b70d60b56fe251cbd',
    messagingSenderId: '984797892872',
    projectId: 'chat-near-by',
    storageBucket: 'chat-near-by.appspot.com',
    iosClientId: '984797892872-4gh80vfjp869urprtq67srnu8036gp31.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatModule',
  );
}
